Fix checkstyle wrappers.
For now, use the version that we supported in the past, 6.14.1.  If we
find it useful, we will upgrade in the future.

Rework the filename convention for downloading based on the checkstyle
version.

For the download condition, make sure we check for the existence of the
file, and that its length is not 0 (-s vs -f).

Remove code relating to prompting the user for downloading checkstyle.
(seems unnecessary, and the python wrapper ignores that anyway).

Make sure we fail when the download (wget) fails. This is picked up by
the python wrapper which throws an exception when we have an error.

Check the wrapper argument list length and exit with 0 immediately if no
argument has been provided (including an info message). This conforms
well to the expectation of the Python script to download the checkstyle
binary when the bash wrapper is called without arguments.  We DO want to
know when the download fails.

Finally, just call checkstyle directly at the end of the bash wrapper,
ensuring that we get the output and the return code.

Change-Id: I2db89b71aeaa15f3af3c5eecb0bd693425d27565

diff --git a/tools/checkstyle/checkstyle b/tools/checkstyle/checkstyle
--- a/tools/checkstyle/checkstyle
+++ b/tools/checkstyle/checkstyle
@@ -3,34 +3,25 @@
 SCRIPT_PATH=$(dirname $0)
 
 CONFIG=$SCRIPT_PATH/config.xml
-CHECKSTYLE_JAR=$SCRIPT_PATH/checkstyle-6.14.1-all.jar
+CHECKSTYLE_VERSION=6.14.1
+CHECKSTYLE_JAR="$SCRIPT_PATH/checkstyle-$CHECKSTYLE_VERSION.jar"
 
-if [ ! -f $CHECKSTYLE_JAR ]; then
-  DOWNLOAD_URL=http://sourceforge.net/projects/checkstyle/files/checkstyle/6.14.1/checkstyle-6.14.1-all.jar/download 
-  SOURCES_URL=https://github.com/checkstyle/checkstyle/tree/checkstyle-6.14.1
-  DOWNLOAD_COMMAND="wget $DOWNLOAD_URL -O $CHECKSTYLE_JAR"
+if [ ! -s $CHECKSTYLE_JAR ]; then
+  DOWNLOAD_URL="https://github.com/checkstyle/checkstyle/releases/download/checkstyle-$CHECKSTYLE_VERSION/checkstyle-$CHECKSTYLE_VERSION-all.jar"
+  SOURCES_URL="https://github.com/checkstyle/checkstyle/tree/checkstyle-$CHECKSTYLE_VERSION"
 
   echo "Downloading the checkstyle jar file at $DOWNLOAD_URL.
   The sources can be found at $SOURCES_URL."
-  # Do not prompt for user input when run non-interactively.
-  if [ -z $PS1 ]; then
-    $DOWNLOAD_COMMAND
-  else
-    read -p "Download (y/n)?" -n 1 -r
-    if [[ ! $REPLY =~ ^y$ ]]
-    then
-      echo -e "\nCannot run checkstyle. Exiting."
-      exit 1
-    else
-      $DOWNLOAD_COMMAND
-    fi
+
+  if ! wget "$DOWNLOAD_URL" -O "$CHECKSTYLE_JAR"; then
+    echo "Download failed."
+    exit 1
   fi
 fi
 
-output=$(java  -jar $CHECKSTYLE_JAR -c $CONFIG "$@")
-echo "$output"
-
-# We want to return an error code if linting errors were found.
-if echo "$output" | grep "error" &> /dev/null ; then
-  exit 1
+if [ "$#" -lt 1 ]; then
+  echo "No argument provided. Exiting."
+  exit 0
 fi
+
+java  -jar $CHECKSTYLE_JAR -c $CONFIG "$@"
